[project]
name = "mcp-auth-debug-server"
version = "0.1.0"
description = "MCP server for debugging authorization header handling"
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["mcp[cli]>=1.11.0"]
